version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-west-2)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $ECR_REPO:latest
      - docker tag $ECR_REPO:latest $ECR_REPO:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:latest
      - echo Writing image definitions file...
      - printf '[{"name":"hello-world","imageUri":"%s"}]' $xECR_REPO:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
